<a href="https://colab.research.google.com/github/BenAtigIbrahim/matrix/blob/main/exercice_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Matrix (erray) exercise***

**step 1 : create a Matrix**

In [ ]:
# Matrix 2 rows an 3 columns
matrix=([10,2,3],
        [8,6,10])
print("this is my matrix: ", matrix)

this is my matrix:  ([10, 2, 3], [8, 6, 10])


***step 2 :Identify the data type of the matrix and calculate the mean, mode and median of the data.***

In [ ]:
# Data type of the matrix
import numpy as np
matrix=np.array([[10,2,3],
                 [8,6,10]])
data_type = matrix.dtype
print("Data type of the matrix:", data_type)   # matrix is a némurical data

Data type of the matrix: int64


In [ ]:
# calculate the mean
mean_value=np.mean(matrix)
print("the mean value of matrix : " , mean_value)

the mean value of matrix :  6.5


In [ ]:
# calculate the médian :
median_value = np.median(matrix)
print("the median of matrix :", median_value)

the median of matrix : 7.0


In [ ]:
# calculate the mode : j'Essaye de trouver le mode avec scipy
from scipy import stats
mode = stats.mode(matrix, axis=None)
print("the Mode of matrix :", mode)

the Mode of matrix : ModeResult(mode=10, count=2)


***step 3 : Perform basic matrix operations (addition, subtraction, transpose and scalar multiplication) on the matrix***

In [ ]:
# Assuming we have another matrixB for operations
matrixB = ([1,2,3],
          [4,5,6])
matrixB = np.array([[1,2,3],
                    [4,5,6]])
print("this my MatrixB : " , matrixB)

this my MatrixB :  [[1 2 3]
 [4 5 6]]


In [ ]:
# addition : matrix + matrixB
addition_value = np.add(matrix, matrixB)
print("the addition of matrix + matrixB : " , addition_value)

the addition of matrix + matrixB :  [[11  4  6]
 [12 11 16]]


In [ ]:
# subtraction : matrix - matrixB
subtraction_value = np.subtract(matrix, matrixB)
print("the subtraction of matrix - matrixB : " , subtraction_value)

the subtraction of matrix - matrixB :  [[9 0 0]
 [4 1 4]]


In [ ]:
# transpose matrix :
transpose_matrix = np.transpose(matrix)
print("the transpose of matrix : " , transpose_matrix)

the transpose of matrix :  [[10  8]
 [ 2  6]
 [ 3 10]]


In [ ]:
# transpose matrixB
transpose_matrixB = np.transpose(matrixB)
print("transpose of matrixB : " , transpose_matrixB)

transpose of matrixB :  [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# scalar multiplication 3*matrix
scalar_multiplication_result = 3 * matrix
print("multiplication matrix result : ", scalar_multiplication_result)

multiplication matrix result :  [[30  6  9]
 [24 18 30]]


In [ ]:
# scalar multiplication 5*matrixB
scalar_multiplication_result = 5 * matrixB
print("multiplication matrixB result : ", scalar_multiplication_result)

multiplication matrixB result :  [[ 5 10 15]
 [20 25 30]]
